### ISSUE TITLE
10月25日的歌下载后，拖到GO命令行上，提示error，貌似wy改了加密？

### ISSUE THREAD

**Issue by punkhuoye** [xiSage/ncmdump-net#1]
歌是这个http://music.163.com/song?id=2639024679&userid=3365566

**Comment by xiSage** [comment]
我测试了一下，没有遇到错误，可以请你发一下报错的内容看看吗。
另外，这个仓库是ncmdump-net，不是ncmdump或者ncmdump-go，如果你是在使用后面两个项目时遇到的问题，请到对应的仓库报告问题；或者尝试使用本仓库发布的二进制文件，在我上面的测试中，ncmdump-net可以正确转换你发的这首歌。

**Comment by punkhuoye** [comment]
升级网易云到3.0.3后，下载的SQ级别的歌曲可以转换了。我之前用的是2.7.1版本。给大佬添麻烦了，我用的是您的NET版本，其他两个项目会显示乱码。
